---
abstract: 'ZofCMS plugin that redirects the user to a page choosen by the user'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-StartPage
provides:
  App::ZofCMS::Plugin::StartPage:
    file: lib/App/ZofCMS/Plugin/StartPage.pm
    version: 0.0102
requires:
  App::ZofCMS::Plugin::Base: 0.0106
  DBI: 1.609
  HTML::Template: 2.9
resources:
  license: http://dev.perl.org/licenses/
version: 0.0102
