---
abstract: 'ZofCMS plugin that redirects the user to a page choosen by the user'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-StartPage
provides:
  App::ZofCMS::Plugin::StartPage:
    file: lib/App/ZofCMS/Plugin/StartPage.pm
    version: 0.0103
requires:
  App::ZofCMS::Plugin::Base: 0.0106
  DBI: 1.609
  HTML::Template: 2.9
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.0103
